ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      # NB. To avoid sometimes needing multiple runs, we need:
      # - trailing-whitespace BEFORE end-of-file-fixer,
      #   otherwise trailing newline followed by whitespace, "\n ",
      #   will need multiple runs.
      # - end-of-file-fixer   BEFORE mixed-line-ending,
      #   otherwise a file with CRLF line endings but missing a trailing
      #   newline will need multiple runs.
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-github-workflows

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: "npx eslint src/*"
        language: node
        types_or: [ts, tsx, javascript, jsx]
