name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            ./.tests/requirements-dev.txt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev gir1.2-atspi-2.0

          sudo apt install -y
      - name: Verify system dependencies
        run: |
          dpkg -l | grep python3-gi
          dpkg -l | grep libgirepository1.0-dev
          /usr/bin/python3 -c "import gi; print(gi.__file__)"

      - name: Install Python dependencies
        run: /usr/bin/python3 -m pip install -r ./.tests/requirements-test.txt

      - name: Run tests
        run: /usr/bin/python3 -m pytest ./.tests/test_server.py -rP
